server:
  port: 8080


spring:
#  profiles:
#    active: @spring.profiles.active@
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    url: jdbc:mysql://itineraryplanner.cptumifiqa9a.ap-southeast-1.rds.amazonaws.com:3306/itineraryplanner
    username: admin
    password: jtctlyjwwfpatjh3134$
    driverClassName: com.mysql.cj.jdbc.Driver
  mail:
    host: ${mail.host}
    port: ${mail.port}
    username: ${mail.email}
    password: ${mail.password}
    protocol: smtps
    properties:
      mail:
        smtps:
          auth: ${mail.properties.mail.smtp.auth}
        starttls:
          enable: ${mail.properties.mail.smtp.auth.starttls.enable}


aws:
  region: ap-southeast-1
  s3:
    buckets:
      account: ip-account