spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://${database.host}:${database.port}/${database.schema}
    username: ${database.username}
    password: ${database.password}
    driverClassName: com.mysql.jdbc.Driver
    show-sql: true

