# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  applicationfolder: itineraryplanners-backend
  AWS_REGION: ap-southeast-1
  S3BUCKET: codepipeline-ap-southeast-1-138889920472

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Upload Artifacts
      working-directory: ./target
      run: aws s3 cp *.war s3://${{ env.S3BUCKET }}/
      
#     - name: Generate Deployment Package
#       run: zip -r deploy.zip . -x '*.git*'
      
#     - name: Deploy to EB
#       uses: einaregilsson/beanstalk-deploy@v21
#       with:
#           aws_access_key: AKIA4GGI5G64P7R6WT6O
#           aws_secret_key: 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
#           application_name: itineraryplanners
#           environment_name: Itineraryplanners-env
#           version_label: 12345
#           region: ap-southeast-2
#           deployment_package: deploy.zip
      
